export default OrgPost = [
      { key: '1', value: 'HEINZ' },
      { key: '2', value: 'Русские пекари' },
      { key: '3', value: 'VICI' },
      { key: '4', value: 'Агуша' },
      { key: '5', value: 'Dove' },
      { key: '6', value: 'Овощебаза' },
      { key: '7', value: 'Мираторг' },
      { key: '8', value: 'Горячая штучка' },
      { key: '9', value: 'Останкино' },
      { key: '10', value: 'Черкизово' },
      { key: '11', value: 'Чистая линия' },
      { key: '12', value: 'Коровка из кореновки' },
      { key: '13', value: 'Дядя Ваня' },
      { key: '14', value: 'Maggi' },
      { key: '15', value: 'Nescafe' },
      { key: '16', value: 'Фруто-Няня' },
      { key: '16', value: 'Макфа' },
      { key: '16', value: 'FishHouse' },
      { key: '16', value: 'Черноголовка' },
]